services:
  node:
    build: .
    volumes:
      - ./:/app
      - ./db.json:/app/db.json
    ports:
      - "3000:3000"
    command: npx json-server --watch db.json --port 3000
    networks:
      - app-network
  expo:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "8081:8081"
    environment:
      - EXPO_DEVTOOLS_LISTEN_PORT=19006
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
